name: Build and push file

on:
  push:
    branches:
      - master
    
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build --if-present
      env:
        CI: true

  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: roland-burke/ScotlandYardServer@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'build/*'
        destination_repo: 'roland-burke/ScotlandYardServer'
        destination_folder: 'public/ScotlandYardFrontend'
        user_email: 'action@example.com'
        user_name: 'roland-burke'
        commit_message: 'Automatic commit by git action from ScotlandYardFrontend'
